library(ggplot2) 
attach(diamonds) 
View(diamonds)
help(diamonds)
head(diamonds)
dim(diamonds) 
names(diamonds)
str(diamonds)
nrow(diamonds) 
ncol(diamonds) 
summary(diamonds)

fivenum(x, na.rm=TRUE)
stem(x)		
hist(x)
lines(density(x,na.rm=TRUE,bw=1.))
rug(x) 
fivenum(y, na.rm=TRUE)
stem(y)		 
hist(y)
lines(density(y,na.rm=TRUE,bw=1.))
rug(y) 
fivenum(z, na.rm=TRUE)
stem(z)		 
hist(z)
lines(density(z,na.rm=TRUE,bw=1.))
rug(z) 

fivenum(price, na.rm=TRUE)
#boxplot(price)
stem(price)		 # stem and leaf plot
hist(price)
lines(density(price,na.rm=TRUE,bw=1.))
rug(price) 

diamonds2 <- diamonds %>% filter(between(y, 3, 20))

fivenum(carat, na.rm=TRUE)
stem(carat)		
hist(carat)
lines(density(carat,na.rm=TRUE,bw=1.))
rug(carat) 
